# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: required
cache: packages

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install -y libxml2
  - sudo apt-get install -y libudunits2-dev
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev
  - sudo apt-get install texlive-latex-recommended

r:
  - oldrel
  - release
  - devel

r_packages:
  - devtools
  - R6
  - XML
  - sf
  - testthat
  - covr

r_check_args: --as-cran

after_script:
 - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
